spring:
  datasource:
    username: root
    password: 142843827Ccq!
    #serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://49.234.82.226:3306/small?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


# 整合mybatis
mybatis:
  type-aliases-package: com.ccqstark.small.model
  mapper-locations: classpath:mapper/*.xml
